export struct BMSInfoModel {
    state: [int],
    cell_voltage: [float],
    balance: [int],
    voltage: float,
    current: float,
    temperature: float,
    soc: float,
    soh: float,
    dsg: bool,
    chg: bool,
}


export global BMSModelService {
    in-out property <BMSInfoModel> bms-info;
    pure callback build-v-plot(length, length) -> image;
    pure callback build-c-plot(length, length) -> image;
}