
import { VerticalBox } from "std-widgets.slint";
export component Plot inherits Rectangle {
    background: #ffffff;
    border-radius: 5px;
    drop-shadow-blur: 10px;
    drop-shadow-color: #eee;
    drop-shadow-offset-x: 10px;
    drop-shadow-offset-y: 10px;

    height: 150px;

    in property <image> source <=> img.source;

    in property <string> title;

    VerticalBox { 
        Text {
            horizontal-alignment: left;
            text: title;
            font-size: 14px;
            color: #999;
        }
        img := Image {}
     }
}