import { VerticalBox , HorizontalBox} from "std-widgets.slint";
export component IndexWidget inherits Rectangle {
    background: #fffa;
    VerticalBox { 
        alignment: center;
        Text {
            horizontal-alignment: center;
            text: @tr("CawLink");
            color: #000000;
            font-size: 60px;
            font-weight: 800;
        }

        Text {
            horizontal-alignment: center;
            text: @tr("search device ...");
            color: #666;
            font-size: 20px;
        }

        HorizontalBox {
            alignment: center;
            Rectangle {
                border-radius: 5px;
                background: red;
                height: 5px;
                width: 200px * abs(sin(360deg * animation-tick() / 3s));
            }
        }
    }
}